name: toko-bluefin
id: toko-bluefin
stages:
  - id: build
    # NOTE: Can't get vanilla to work yet on my desktop machine
    # base: ghcr.io/vanilla-os/nvidia:main
    base: ghcr.io/ublue-os/bluefin-nvidia
    singlelayer: false
    labels:
      maintainer: self-maintained
    # args:
    #   DEBIAN_FRONTEND: noninteractive
    # runs:
    #   commands:
    #     - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends
    modules:
      # - name: vanilla-os--pre
      #   type: includes
      #   includes:
      #     - modules/vanilla-os/pre.yml

      ################################################
      # Put your custom actions behind this comment
      ################################################

      # NOTE: Already installed on bluefin
      # - name: tailscale
      #   type: includes
      #   includes:
      #     - modules/tailscale/install.yml

      - name: gnome
        type: includes
        includes:
          # NOTE: Don't need to install gnome-tweaks on bluefin
          # - modules/gnome/dependencies.yml
          - modules/gnome/install-whitesur-theme.yml

      - name: apps
        type: includes
        includes:
          # - modules/apps/1password.yml
          - modules/apps/install.yml

      - name: shell
        type: includes
        includes:
          - modules/shell/install.yml

      ################################################
      # Put your custom actions before this comment
      ################################################

      # - name: vanilla-os--post
      #   type: includes
      #   includes:
      #     - modules/vanilla-os/post.yml
